# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 810dc378fa950761b99af76a98dfd22e0427c29e53976f58e3c7869c1cfbf7e3bc798edff78b88554283690db47dc473b04a4d9fc0290ca5b7f5aca8a122195c

test:
  secret_key_base: a0bbf8dd35cf887d28bddd210cecc04f0fd4b734016a0bb0e7c7f01160040b8c9ef1372ae75e53b5e0077538e5096f209b8d076aad715d32d643df9965178a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
